// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logos/PrimaryLogo.tsx": () => import("../components/mockups/logos/PrimaryLogo.tsx"),
  "./components/mockups/logos/SecondaryLogo.tsx": () => import("../components/mockups/logos/SecondaryLogo.tsx"),
  "./components/mockups/logos/Submark.tsx": () => import("../components/mockups/logos/Submark.tsx")
};
